version: "3.9"

services:
    postgres-db:
      image: postgres:alpine
      container_name: postgres-db
      environment:
        POSTGRES_USER: camopu
        POSTGRES_PASSWORD: pgpassword
        POSTGRES_DB: fastify-db
      volumes:
        - ./postgres/postgres.conf:/usr/local/etc/postgres/postgres.conf
        - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
        - ./database:/var/lib/postgresql/data
      command: postgres -c config_file=/usr/local/etc/postgres/postgres.conf
      ports:
        - "5432:5432"
      restart: unless-stopped
      networks:
        - app-network

    nodejs-api:
      build:
        context: .
        dockerfile: Dockerfile
      image: nodejs:alpine
      container_name: fastify-api
      restart: unless-stopped
      depends_on:
        - postgres-db
      ports:
        - "3000:3000"
      restart: unless-stopped
      networks:
        - app-network

volumes:
  database:

networks:
  app-network:
    driver: bridge
